"""empty message

Revision ID: b183b7ad2e93
Revises: c89e7fb0b588
Create Date: 2025-02-23 16:20:03.894158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b183b7ad2e93'
down_revision = 'c89e7fb0b588'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_mydatabase_alt():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alt_user',
    sa.Column('id', sa.Integer(), nullable=False, comment='Unique identifier for the user'),
    sa.Column('username', sa.String(length=10), nullable=False, comment='Username of the user'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_mydatabase_alt():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alt_user')
    # ### end Alembic commands ###

