"""empty message

Revision ID: c89e7fb0b588
Revises: 
Create Date: 2025-02-23 16:16:22.039618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c89e7fb0b588'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False, comment='Unique identifier for the user'),
    sa.Column('username', sa.String(length=10), nullable=False, comment='Username of the user'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def upgrade_mydatabase_alt():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_mydatabase_alt():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

