# Dev Containerではこちらが優先される。
services:
  flask_app:
    build:
      target: devcontainer
      context: .
      dockerfile: Dockerfile
    image: flask-devcontainer:latest
    container_name: flask-devcontainer-container
    volumes:
      - ./:/flask # contextから見たパスではなく，リポジトリから見たパスがvolume mountされる。
      # NOTE: ./install-pkg.shでインストールしたパッケージをキャッシュするためのディレクトリ
      - ./.devcontainer/cache:/cache
  mysql_svr:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
